# Environment
#-------------------------------------------------------------------------------
DEBUG: True
CONFIG_DIR: '~/.hydropi'

# Hardware pins
#-------------------------------------------------------------------------------

# Inputs
CHANNEL_PH: 0        # Channels 0-7
CHANNEL_EC: 1
CHANNEL_PRESSURE: 2
PIN_DEPTH_TRIG: 4
PIN_DEPTH_ECHO: 5

# MSP3008 ADC chip
PIN_CS:   8   # Chip select
PIN_MISO: 9   # Din
PIN_MOSI: 10  # Dout
PIN_CLK: 11   # CLK

# Outputs
PIN_PRESSURE_PUMP: -1
PIN_MIST_VALVE: -1
PIN_NUTRIENT_PUMP: -1
PIN_PH_DOWN_PUMP: -1
PIN_WATER_VALVE: -1
PIN_MIX_PUMP: -1

# Parameters
#-------------------------------------------------------------------------------

# Timing
SWEEP_CYCLE_MINUTES: 15
MIST_CYCLE_MINUTES: 5
MIST_DURATION_SECONDS: 15
MIX_PUMP_SECONDS: 60
MIX_ADDITION_DELAY_SECONDS: 10
WATER_FILL_INTERVAL_SECONDS: 10
WATER_FILL_MAX_SECONDS: 60
QUIET_TIME_START: "20:00"
QUIET_TIME_END: "07:00"

# Pressure monitoring
MIN_PRESSURE_PSI: 100
MAX_PRESSURE_PSI: 140
ALERT_PRESSURE_PSI: 90

# PH monitoring
PH_TARGET: 6.0
PH_LIMIT_WARN: 0.5
PH_LIMIT_DANGER: 1
PH_ACTION_THRESHOLD: 0.25
PH_ACTION_THRESHOLD: 10

# EC monitoring
EC_TARGET: 1.8
EC_LIMIT_WARN: 0.4
EC_LIMIT_DANGER: 1
EC_ACTION_THRESHOLD: 0.2
EC_ADDITION_SECONDS: 2

# Water level monitoring
TANK_HEIGHT_MM: Null            # Total distance between head sensor and tank bottom (e.g. 225mm)
DEPTH_MAXIMUM_MM: Null          # Depth units when full (e.g. 200mm)
DEPTH_LIMIT_WARN: 0.75          # 75% full
DEPTH_LIMIT_DANGER: 0.5
DEPTH_ACTION_THRESHOLD: 0.75

# Database connection
#-------------------------------------------------------------------------------

# Read live config from database (will override default config in this file)

# DATABASE:
#   - SQLITE_PATH: "db.sqlite"
#   - CONFIG_TABLE_NAME: "dash_config"
#   - CONFIG_VALUE_FIELD: "key"
#   - CONFIG_KEY_FIELD: "value"
#   - READINGS_TABLE_NAME: "dash_reading"
